title: Think Responsibly Show
description: Empowering informed citizens through media literacy and civic engagement.
baseurl: "/thinkresponsiblyshow"
url: "https://volanalytics.github.io"
permalink: /:year/:month/:day/:title
plugins:
  - jekyll-feed
# Added to trigger rebuild
